[project]
name = "dbt-data-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-duckdb>=1.9.4",
    "dlt[duckdb,parquet]>=1.15.0",
]
